In [18]:
import torch as t
import numpy as np

In [4]:
x = t.rand(2)
print(x)

tensor([0.2264, 0.8438])


In [5]:
x = t.rand(2,2)
print(x)

tensor([[0.0617, 0.9219],
        [0.5609, 0.4012]])


In [7]:
x = t.rand(2,2,2)
print(x)

tensor([[[0.4397, 0.1274],
         [0.8401, 0.3264]],

        [[0.1486, 0.2400],
         [0.8567, 0.9918]]])


In [8]:
x.shape

torch.Size([2, 2, 2])

In [9]:
x = t.zeros(2)
print(x)

tensor([0., 0.])


In [10]:
x = t.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [12]:
x = t.zeros(2,2,2)
print(x)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])


In [13]:
x=t.ones(2)
print(x)

tensor([1., 1.])


In [14]:
x=t.ones(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [15]:
x=t.ones(2,2,2)
print(x)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])


In [16]:
x=t.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [19]:
x=t.tensor([[5.5,3],[4,6]])
print(x)

tensor([[5.5000, 3.0000],
        [4.0000, 6.0000]])


In [20]:
x=t.rand(2,3)
y=t.rand(2,3)
result=x+y
result

tensor([[0.9643, 0.9626, 1.2554],
        [1.3449, 1.0620, 1.0930]])

In [22]:
x_transpose=x.t()

result=t.mm(x,x_transpose)
result

tensor([[1.4020, 0.5501],
        [0.5501, 0.8841]])

In [23]:
x=torch.ones(3,3)
print(x)

y=x+10
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[11., 11., 11.],
        [11., 11., 11.],
        [11., 11., 11.]])


In [25]:
x=t.ones(3,3,requires_grad=True)
print(x)

y=x+10
print(y)
y=x*10
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor([[11., 11., 11.],
        [11., 11., 11.],
        [11., 11., 11.]], grad_fn=<AddBackward0>)
tensor([[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]], grad_fn=<MulBackward0>)


In [26]:
x=t.randn(3,3)
x=((x*3)/(x-1))
print(x.requires_grad)

x.requires_grad_(True)
print(x.requires_grad)

y=(x*x).sum()
print(y)
print(y.grad_fn)

False
True
tensor(163.3926, grad_fn=<SumBackward0>)


In [28]:
x=t.randn(3,3,requires_grad=True)
y=((x*3)/(x-1))

z=(x*x).sum()

print(z)
print(z.grad_fn)

z.backward()
print(x.grad)

tensor(19.0451, grad_fn=<SumBackward0>)
tensor([[ 3.3335,  3.5395,  0.1811],
        [ 2.8771,  1.3457, -3.6202],
        [ 2.2840,  1.4353,  4.6942]])
